services:
  hugo:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - ./:/src:cached
    environment:
      - HUGO_ENV=development
    command: hugo server -D --bind 0.0.0.0 --port 1313 --disableFastRender
