name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (not required but ensures environment)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create output
        run: |
          mkdir -p public
          cp -r index.html about.html publications.html assets cv.pdf .nojekyll public/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
